apiVersion: v1
kind: Service
metadata:
  name: nextapp
  labels:
    app: nextapp
spec:
  ports:
    - port: 80
    - targetPort: 3000
  selector:
    app: nextapp
    tier: frontend
  type: LoadBalancer
