apiVersion: v1
kind: Service
metadata:
  name: nextapp
  labels:
    app: nextapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: nextapp
    tier: frontend
  type: LoadBalancer
