version: 2.1

workflows:
  test-deploy:
    jobs:
      - build

orbs:
  node: cimg/node:21.6.1
  
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        - pkg-manager: npm
      - run:
        - name: Build the project
        - command: npm run build
      - persist_to_workspace:
        - root: ~/project
        - paths:
          - .
  
