version: 2.1

orbs:
  node: circleci/node@5
  
workflows:
  build-workflow:
    jobs:
      - build

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Create ~/artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
