version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
  
jobs:
  test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - node/install-packages:
        - pkg-manager: npm
      - run:
        - name: Build the project
        - command: npm run build

  
