version: 2.1

orbs:
  node: circleci/node@5
  
workflows:
  build-workflow:
    jobs:
      - build

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          - pkg-manager: npm
      - run:
          name: Build the project
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
